### ISSUE TITLE
Some questions concerning the references and if conditions

### ISSUE THREAD

**Issue by izsahara** [fp2556/onlinesvr#3]
If we refer to the main reference for the algorithm (as mentioned in your website) **Accurate Online Support Vector Regression,
Ma, Theiler, Perkins, Article, 2003** There are just some details in the source code I would like some clarification on.

1. In the function _FindGamma_ (OnlineSVR.cpp)  if the Support Vector Set is empty, the gamma vector is filled with ones of size number of training examples stored.  In Ma et al. the reference shows that the gamma vector is calculated from the kernel output of samples in set N (E \union R) summed with the product of R matrix and Beta vector (Qnc + (R*Beta)). Thus, in the case where the S set is empty, the gamma vector should only contain the kernel outputs from the samples in set N. **Now initially, if all sets (R, E and S) are empty shouldn't gamma be empty? Why fill it with ones and what is the reference to this choice?**
2. Following from 1,  Ma et al. tackles this issue by initialization of the incremental algorithm by using a two sample solution to fill the E and R sets (Section 3.4 in the paper) . Is there a particular reason you did not include this (from my knowledge of reading your code)?
3. Would this be a 'Error' of the paper that you stated in your master thesis in which you have corrected? If so, what are the said errors you have found in the paper?

Thanks,

**Comment by fp2256** [comment]
H Izsahara, you made some very good points. It has been more than 10 years since I wrote this code and the thesis, so I suggest to take a look at it for more detailed information. You can find it in the [repository](https://github.com/fp2556/onlinesvr/blob/master/papers/Online%20Support%20Vector%20Regression%20(Parrella%20F.)%20%5B2007%5D.pdf).

Concerning the implementation, I had to make several modifications to the original AOSVR algorithm, especially in order to fix the stabilization problem I faced (you can find more details in the thesis).

This version, compared to the referred paper, also allows additions and removals of samples, so it always needs to have a value of gamma, and it is not possible to pre-train it because then it would not allow the case of having all the elements removed.

Concerning Gamma, I do not think it matters too much what the initial value is as long as the KKT conditions are always verified, and in any case, it would quickly converge to the optimal value.

**Comment by izsahara** [comment]
Thanks for the info, also Id like to ask.
So when training the model, we import ALL training data into the model and then for each sample we place into learning. Now when calculating the Q matrices for beta and gamma do we use the WHOLE imported training data OR the samples that have already been trained? i.e. when calculating Q, (this->X) points to the WHOLE training data set (trained+untrained) OR just the trained samples?

**Comment by fp2256** [comment]
The learning is online, so at each given time, only one new data point is added (or removed). Hence, untrained samples are not used.
For calculating the Q matrices you do not need the whole training data, but only the elements in the support set. You can find more info [here](https://github.com/fp2556/onlinesvr/blob/master/papers/Online%20Support%20Vector%20Regression%20(Parrella%20F.)%20%5B2007%5D.pdf).

**Comment by izsahara** [comment]
Yes, I just realized. Essentially im translating your C++ code into a python script (with simplifications and a structure that makes it clear to me) for educational purposes (to both learn C++ and how the algorithm works). I applaud you for the clear and concise code though, well documented as well (quite rare nowadays)! Have you considered extending your research to Online nu-SVR?

**Comment by fp2256** [comment]
It is a good idea. When it is completed, if you want we can host it here. 
At the moment I am not much involved in research, it would be nice to have an online nuSVR.

**Comment by izsahara** [comment]
Hi Francesco,
Just a short back story as to why I was interested in Online SVR's and
subsequently your work.
So I'm coming from a background in Aerospace Engineering, and at the time I
asked the question was when I was writing my Bachelor's thesis. Which in a
nutshell is surrogate modelling with SVR for a specific aerospace data set.
Of course this is rather simplistic (and therefore not publishable) so the
addition of online learning would be more appropriate (since aerospace data
is highly expensive).

Currently i'm doing a Masters thesis on deep gaussian processes (a whole
new topic in of itself) but i've still yet to publish some work on SVR.
Since then I've been more focused on Bayesian SVR, which I'm still
interested in seeing if this can be coupled with an online learning
algorithm.

When getting back to my research on SVR i'll try to couple this with your
code, and yes maybe in our spare time we can host a project (i don't think
there's much research code on SVR in github from what i see, just your
standard sklearn stuff). Thanks for the reply.

Regards,
Faiz
